const lstReview = [
    {
        key: 1,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21,
        time: "20/04/2022"
    },
    {
        key: 2,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 3,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 4,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 5,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 6,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 7,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 8,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 9,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 10,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 11,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 12,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 13,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 14,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 15,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 16,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 17,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 18,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 19,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 20,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 21,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 22,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 23,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 24,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 25,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 26,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 27,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    },
    {
        key: 28,
        user: "Thức ngok ngek trái tym ák qỉ",
        title: "[REVIEW] Doraemon: Nobita Và Cuộc Chiến Vũ Trụ Tí Hon 2021 (2022)",
        content: "Doraemon: Nobita và mặt trăng phiêu lưu ký vẫn mang đến cho khán giả những thông điệp dành cho nhiều lứa tuổi khác nhau, như cách các tập phim khác vẫn truyền tải. Cha mẹ dù có bất cứ hành động gì thì trong trái tim họ vẫn là tình yêu thương và sẵn sàng bảo vệ con cái của mình bất chấp tính mạng, những người bề ngoài có thể là một người xấu nhưng bên trong họ là lý do cao cả mà không ai có thể hiểu được và tình bạn là luôn sẵn sàng vì nhau mà chiến đấu chống lại những kẻ xấu. Cuối cùng mỗi người đều phải quay trở về với cuộc sống của mình, nhưng tình bạn không vì thế mà chấm dứt mà trong tim mỗi người đều có hình bóng của người kia.Doraemon: Nobita và mặt trăng phiêu lưu ký chắc chắn sẽ khiến khán giả không phải thất vọng với những nét vẽ quen thuộc với độc giả và khán giả nhiều năm qua. Nobita vẫn hậu đậu và mít ướt, Doraemon vẫn mê bánh rán, Shizuka vẫn thích ngâm mình trong bồn tắm, Jaian vẫn sở hữu giọng hát đáng sợ như xưa, Suneo vẫn ích kỉ như cũ. Những hình ảnh trong phim được tái hiện rất đẹp, đặc biệt là cảnh bầu trời đêm và khi những người bạn trên mặt trăng thể hiện sức mạnh. Tất cả khiến khán giả nhí trầm trồ thích thú.\nPhần âm thanh của Doraemon lần này được đầu tư rất tốt khi sử dụng được tất cả hệ thống âm thanh đa kênh trong rạp. Những tiếng cháy nổ, cảnh chiến đấu khiến người xem phải giật mình vì quá mức chân thực, khán giả theo dõi bản phụ đề sẽ cảm nhận rõ điều này.\nBản lồng tiếng lần này chưa thực sự tốt khi Doraemon nghe khá chói tai, khiến cảm xúc của người xem đôi khi phải chững lại. Vậy nên nếu không phải đi với các em nhỏ thì các bạn nên lựa chọn bản phụ đề theo dõi để cảm nhận trọn vẹn được cái hay của bộ phim.Doraemon: Nobita và mặt trăng phiêu lưu ký hiện đang được công chiếu tại Touch Cinema. Đừng bỏ lỡ tác phẩm thú vị này nhé.\nChúc các bạn xem phim vui vẻ!",
        like: 120,
        share: 20,
        cmt: 21
    }
]

export default lstReview;